<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="pytest" skips="0" tests="2" time="0.145"><testcase classname="test_class.TestClass" file="test_class.py" line="6" name="test_one" time="0.000720977783203"></testcase><testcase classname="test_class.TestClass" file="test_class.py" line="11" name="test_two" time="0.015472650528"><failure message="assert &apos;hi&apos; == &apos;hello&apos;
  - hi
  + hello">self = &lt;test_class.TestClass object at 0x7f6a13683a90&gt;

    def test_two(self):
        x = &apos;hello&apos;
&gt;       assert &quot;hi&quot; == x
E       assert &apos;hi&apos; == &apos;hello&apos;
E         - hi
E         + hello

test_class.py:14: AssertionError</failure></testcase></testsuite>